### ISSUE TITLE
sam init looking for template quick-start-from-scratch

### ISSUE THREAD

**Issue by ashrimp** [aws/aws-sam-cli-app-templates#261] opened 2022-06-18 21:20 UTC
### Description:
sam init looking for template quick-start-from-scratch but the pacakges under nodejs14.x have been renamed to add prefix cookiecutter-xxxx and hence the sam init is failing with error

Error: Can't find application template quick-start-from-scratch - check valid values in interactive init.

### Steps to reproduce:
execute sam init

### Observed result:
Error: Can't find application template quick-start-from-scratch - check valid values in interactive init.

### Expected result:
expected to find the template and install it

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 11
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.52.0
3. AWS region:

`Add --debug flag to any SAM CLI commands you are running`

**Comment by mildaniel** [comment] 2022-06-27 15:55
I tried doing a `sam init` flow with version 1.52.0 and creating a nodejs14.x app and it seemed to work fine. Are there any other steps you can give to help us reproduce?

**Comment by hawflau** [comment] 2022-06-29 03:10
Closing as it seems a duplicate of aws/aws-sam-cli#3946.

@ashrimp please move the discussion to aws/aws-sam-cli#3946, and let us know if the workaround doesn't work for you. Also note that we will have a fix in the upcoming release.

**Closed by hawflau** 2022-06-29 03:10 UTC
Labels: type/bug
