### ISSUE TITLE
Bug: SAM init - graalvm runtime error 

### ISSUE THREAD

**Issue by stanfan1992** [aws/aws-sam-cli-app-templates#260] opened 2022-06-17 03:33 UTC
### Description:

When using `sam cli` with runtime Java11 gradle dependency, `sam build` failed

### Steps to reproduce:

sam init
	1 - AWS Quick Start Templates
	1 - Hello World Example
	7 - java11
	1 - gradle

docker build succeed, but failed on sam build
### Observed result:

With `--debug` flag, we have: 
```
022-06-09 09:41:08,428 | Failed to download image with name e
2022-06-09 09:41:08,428 | Container was not created. Skipping deletion
2022-06-09 09:41:08,431 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 
'5777cbe1-b34f-4f54-a341-afb978bc8fb3', 'installationId': 'dead4f56-46b4-499b-9ed6-b28fe0cdc08a', 'sessionId': 
'508b3787-6163-49ec-affa-758d322ef03c', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.13', 
'samcliVersion': '1.51.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 
'sam build', 'metricSpecificAttributes': {'projectType': 'CFN'}, 'duration': 3623, 'exitReason': 
'DockerImagePullFailedException', 'exitCode': 255}}]}
2022-06-09 09:41:09,257 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', 
port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/docker/api/client.py", line 
261, in _raise_for_status
    response.raise_for_status()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/requests/models.py", line 
943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: 
http+docker://localhost/v1.35/images/create?tag=latest&fromImage=e

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File 
"/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/samcli/local/docker/manager.py", 
line 160, in pull_image
    result_itr = self.docker_client.api.pull(image_name, tag=tag, stream=True, decode=True)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/docker/api/image.py", line 
415, in pull
    self._raise_for_status(response)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/docker/api/client.py", line 
263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/docker/errors.py", line 31, 
in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("pull access denied for e, repository does not exist 
or may require 'docker login': denied: requested access to the resource is denied")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File 
"/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/samcli/local/docker/manager.py", 
line 85, in create
    self.pull_image(image_name)
  File 
"/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/samcli/local/docker/manager.py", 
line 163, in pull_image
    raise DockerImagePullFailedException(str(ex)) from ex
samcli.local.docker.manager.DockerImagePullFailedException: 404 Client Error: Not Found ("pull access denied 
for e, repository does not exist or may require 'docker login': denied: requested access to the resource is 
denied")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, 
in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, 
in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, 
in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, 
in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, 
in invoke
    return callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 
73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, 
in invoke
    return callback(*args, **kwargs)
  File 
"/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", 
line 166, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File 
"/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", 
line 124, in wrapped
    return_value = func(*args, **kwargs)
  File 
"/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", 
line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 
87, in wrapper
    return func(*args, **kwargs)
  File 
"/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/samcli/commands/build/command.py", 
line 182, in cli
    do_cli(
  File 
"/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/samcli/commands/build/command.py", 
line 262, in do_cli
    ctx.run()
  File 
"/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/samcli/commands/build/build_context.py", 
line 248, in run
    build_result = builder.build()
  File 
"/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", 
line 219, in build
    return ApplicationBuildResult(build_graph, build_strategy.build())
  File 
"/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", 
line 75, in build
    result.update(self._build_functions(self._build_graph))
  File 
"/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", 
line 85, in _build_functions
    function_build_results.update(self.build_single_function_definition(build_definition))
  File 
"/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", 
line 156, in build_single_function_definition
    result = self._build_function(
  File 
"/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", 
line 642, in _build_function
    return self._build_function_on_container(
  File 
"/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", 
line 816, in _build_function_on_container
    self._container_manager.run(container)
  File 
"/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/samcli/local/docker/manager.py", 
line 115, in run
    self.create(container)
  File 
"/opt/homebrew/Cellar/aws-sam-cli/1.51.0/libexec/lib/python3.8/site-packages/samcli/local/docker/manager.py", 
line 88, in create
    raise DockerImagePullFailedException(
samcli.local.docker.manager.DockerImagePullFailedException: Could not find e image locally and failed to pull 
it from docker.

```

### Expected result:

A succeed build 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. If using SAM CLI, `sam --version`: 1.51.0 and  1.52.0
3. AWS region: any region

`Add --debug flag to any SAM CLI commands you are running`

**Comment by hawflau** [comment] 2022-06-29 03:16
Hey @stanfan1992 thanks for reporting the issue. I confirm that I could reproduce the issue. Here's my debug log:
```
Cloning from https://github.com/aws/aws-sam-cli-app-templates (process may take a moment)

    -----------------------
    Generating application:
    -----------------------
    Name: sam-app
    Runtime: graalvm.java11 (provided.al2)
    Architectures: x86_64
    Dependency Manager: gradle
    Application Template: hello-world
    Output Directory: .
    
    Next steps can be found in the README file at ./sam-app/README.md
        

    Commands you can use next
    =========================
    [*] Create pipeline: cd sam-app && sam pipeline init --bootstrap
    [*] Validate SAM template: sam validate
    [*] Test Function in the Cloud: sam sync --stack-name {stack-name} --watch

...

» sam build --debug
2022-06-28 20:13:44,014 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-06-28 20:13:44,014 | Using config file: samconfig.toml, config environment: default
2022-06-28 20:13:44,014 | Expand command line arguments to:
2022-06-28 20:13:44,014 | --template_file=/Users/lauwing/playground/202206/sam-graalvm-gradle/template.yaml --use_container --build_image=('a', 'l', '2', '-', 'g', 'r', 'a', 'a', 'l', 'v', 'm', ':', 'g', 'r', 'a', 'd', 'l', 'e') --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache 
2022-06-28 20:13:45,071 | 'build' command is called
2022-06-28 20:13:45,072 | Starting Build inside a container
2022-06-28 20:13:45,076 | No Parameters detected in the template
2022-06-28 20:13:45,095 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2022-06-28 20:13:45,095 | There is no customer defined id or cdk path defined for resource ServerlessHttpApi, so we will use the resource logical id as the resource id
2022-06-28 20:13:45,096 | 0 stacks found in the template
2022-06-28 20:13:45,096 | No Parameters detected in the template
2022-06-28 20:13:45,106 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2022-06-28 20:13:45,106 | There is no customer defined id or cdk path defined for resource ServerlessHttpApi, so we will use the resource logical id as the resource id
2022-06-28 20:13:45,107 | 2 resources found in the stack 
2022-06-28 20:13:45,107 | Found Serverless function with name='HelloWorldFunction' and CodeUri='HelloWorldFunction'
2022-06-28 20:13:45,107 | --base-dir is not presented, adjusting uri HelloWorldFunction relative to /Users/lauwing/playground/202206/sam-graalvm-gradle/template.yaml
2022-06-28 20:13:45,112 | Your template contains a resource with logical ID "ServerlessHttpApi", which is a reserved logical ID in AWS SAM. It could result in unexpected behaviors and is not recommended.
2022-06-28 20:13:45,113 | Instantiating build definitions
2022-06-28 20:13:45,113 | No previous build graph found, generating new one
2022-06-28 20:13:45,113 | Unique function build definition found, adding as new (Function Build Definition: BuildDefinition(provided.al2, /Users/lauwing/playground/202206/sam-graalvm-gradle/HelloWorldFunction, Zip, , d6493e5d-c3f6-49d2-b134-d3c6c43e9b93, {}, {}, x86_64, []), Function: Function(function_id='HelloWorldFunction', name='HelloWorldFunction', functionname='HelloWorldFunction', runtime='provided.al2', memory=256, timeout=20, handler='helloworld.App::handleRequest', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='/Users/lauwing/playground/202206/sam-graalvm-gradle/HelloWorldFunction', environment=None, rolearn=None, layers=[], events={'HelloWorld': {'Type': 'HttpApi', 'Properties': {'Path': '/hello', 'Method': 'get', 'ApiId': 'ServerlessHttpApi'}}}, metadata={'SamResourceId': 'HelloWorldFunction'}, inlinecode=None, codesign_config_arn=None, architectures=['x86_64'], function_url_config=None, stack_path=''))
2022-06-28 20:13:45,114 | Building codeuri: /Users/lauwing/playground/202206/sam-graalvm-gradle/HelloWorldFunction runtime: provided.al2 metadata: {} architecture: x86_64 functions: ['HelloWorldFunction']
2022-06-28 20:13:45,114 | Building to following folder /Users/lauwing/playground/202206/sam-graalvm-gradle/.aws-sam/build/HelloWorldFunction
2022-06-28 20:13:47,508 | Failed to download image with name e
2022-06-28 20:13:47,508 | Container was not created. Skipping deletion
2022-06-28 20:13:47,510 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'cfb16bec-6e49-47f0-8013-d77d638f16b2', 'installationId': 'eca419db-4362-4deb-83b9-250ca9359b7b', 'sessionId': '5f0ddabc-a591-45c5-89dc-da7d35dab410', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.13', 'samcliVersion': '1.52.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'metricSpecificAttributes': {'projectType': 'CFN'}, 'duration': 3495, 'exitReason': 'DockerImagePullFailedException', 'exitCode': 255}}]}
2022-06-28 20:13:47,602 | Telemetry response: 200
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/images/create?tag=latest&fromImage=e

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/local/docker/manager.py", line 160, in pull_image
    result_itr = self.docker_client.api.pull(image_name, tag=tag, stream=True, decode=True)
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/docker/api/image.py", line 415, in pull
    self._raise_for_status(response)
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("pull access denied for e, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/local/docker/manager.py", line 85, in create
    self.pull_image(image_name)
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/local/docker/manager.py", line 163, in pull_image
    raise DockerImagePullFailedException(str(ex)) from ex
samcli.local.docker.manager.DockerImagePullFailedException: 404 Client Error: Not Found ("pull access denied for e, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 166, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 124, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/commands/build/command.py", line 182, in cli
    do_cli(
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/commands/build/command.py", line 262, in do_cli
    ctx.run()
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/commands/build/build_context.py", line 248, in run
    build_result = builder.build()
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 219, in build
    return ApplicationBuildResult(build_graph, build_strategy.build())
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 75, in build
    result.update(self._build_functions(self._build_graph))
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 85, in _build_functions
    function_build_results.update(self.build_single_function_definition(build_definition))
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 156, in build_single_function_definition
    result = self._build_function(
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 643, in _build_function
    return self._build_function_on_container(
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 817, in _build_function_on_container
    self._container_manager.run(container)
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/local/docker/manager.py", line 115, in run
    self.create(container)
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/local/docker/manager.py", line 88, in create
    raise DockerImagePullFailedException(
samcli.local.docker.manager.DockerImagePullFailedException: Could not find e image locally and failed to pull it from docker.
```

Looks like there's a bug in expending the `build_image` option. We will check how to fix it.

**Comment by hawflau** [comment] 2022-06-29 04:06
PR #255 should fix the issue

**Comment by hawflau** [comment] 2022-06-29 04:07
Closing as duplicate of #248

**Closed by hawflau** 2022-06-29 04:07 UTC
Labels: type/bug
